# Generated by Django 4.0 on 2021-12-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songSuggestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songsuggestion',
            unique_together={('artistName', 'songName')},
        ),
    ]
